"""initial schema

Revision ID: 71afe56038b5
Revises: 
Create Date: 2026-04-05 13:40:25.777311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71afe56038b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=False),
        sa.Column('firebase_uid', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
        sa.UniqueConstraint('email', name='uq_user_email'),
        sa.UniqueConstraint('firebase_uid', name='uq_user_firebase_uid'),
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_firebase_uid'), 'user', ['firebase_uid'], unique=False)
    op.create_table(
        'agent',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_agent_user_id_user')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_agent')),
    )
    op.create_index(op.f('ix_agent_user_id'), 'agent', ['user_id'], unique=False)
    op.create_table(
        'agent_sandbox',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=False),
        sa.Column('agent_id', sa.Uuid(), nullable=False),
        sa.Column('state', sa.String(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('workspace_volume', sa.String(), nullable=True),
        sa.Column('workspace_path', sa.String(), nullable=True),
        sa.Column('sandbox_id', sa.String(), nullable=True),
        sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_stopped_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_exit_code', sa.Integer(), nullable=True),
        sa.Column('last_error', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], name=op.f('fk_agent_sandbox_agent_id_agent')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_sandbox')),
        sa.UniqueConstraint('agent_id', name='uq_agent_sandbox_agent_id'),
    )
    op.create_index(op.f('ix_agent_sandbox_agent_id'), 'agent_sandbox', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_sandbox_sandbox_id'), 'agent_sandbox', ['sandbox_id'], unique=False)
    op.create_index(op.f('ix_agent_sandbox_workspace_volume'), 'agent_sandbox', ['workspace_volume'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_sandbox_workspace_volume'), table_name='agent_sandbox')
    op.drop_index(op.f('ix_agent_sandbox_sandbox_id'), table_name='agent_sandbox')
    op.drop_index(op.f('ix_agent_sandbox_agent_id'), table_name='agent_sandbox')
    op.drop_table('agent_sandbox')
    op.drop_index(op.f('ix_agent_user_id'), table_name='agent')
    op.drop_table('agent')
    op.drop_index(op.f('ix_user_firebase_uid'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
